// Code generated by protoc-gen-go. DO NOT EDIT.
// source: testpb/test.proto

package testpb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Test struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Test) Reset()         { *m = Test{} }
func (m *Test) String() string { return proto.CompactTextString(m) }
func (*Test) ProtoMessage()    {}
func (*Test) Descriptor() ([]byte, []int) {
	return fileDescriptor_41c67e33ca9d1f26, []int{0}
}

func (m *Test) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Test.Unmarshal(m, b)
}
func (m *Test) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Test.Marshal(b, m, deterministic)
}
func (m *Test) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Test.Merge(m, src)
}
func (m *Test) XXX_Size() int {
	return xxx_messageInfo_Test.Size(m)
}
func (m *Test) XXX_DiscardUnknown() {
	xxx_messageInfo_Test.DiscardUnknown(m)
}

var xxx_messageInfo_Test proto.InternalMessageInfo

func (m *Test) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Test) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetTestRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTestRequest) Reset()         { *m = GetTestRequest{} }
func (m *GetTestRequest) String() string { return proto.CompactTextString(m) }
func (*GetTestRequest) ProtoMessage()    {}
func (*GetTestRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_41c67e33ca9d1f26, []int{1}
}

func (m *GetTestRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTestRequest.Unmarshal(m, b)
}
func (m *GetTestRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTestRequest.Marshal(b, m, deterministic)
}
func (m *GetTestRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTestRequest.Merge(m, src)
}
func (m *GetTestRequest) XXX_Size() int {
	return xxx_messageInfo_GetTestRequest.Size(m)
}
func (m *GetTestRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTestRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTestRequest proto.InternalMessageInfo

func (m *GetTestRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type SetTestResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetTestResponse) Reset()         { *m = SetTestResponse{} }
func (m *SetTestResponse) String() string { return proto.CompactTextString(m) }
func (*SetTestResponse) ProtoMessage()    {}
func (*SetTestResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_41c67e33ca9d1f26, []int{2}
}

func (m *SetTestResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetTestResponse.Unmarshal(m, b)
}
func (m *SetTestResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetTestResponse.Marshal(b, m, deterministic)
}
func (m *SetTestResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetTestResponse.Merge(m, src)
}
func (m *SetTestResponse) XXX_Size() int {
	return xxx_messageInfo_SetTestResponse.Size(m)
}
func (m *SetTestResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetTestResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetTestResponse proto.InternalMessageInfo

func (m *SetTestResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *SetTestResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Question struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Answer               string   `protobuf:"bytes,2,opt,name=answer,proto3" json:"answer,omitempty"`
	Question             string   `protobuf:"bytes,3,opt,name=question,proto3" json:"question,omitempty"`
	TestId               string   `protobuf:"bytes,4,opt,name=test_id,json=testId,proto3" json:"test_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Question) Reset()         { *m = Question{} }
func (m *Question) String() string { return proto.CompactTextString(m) }
func (*Question) ProtoMessage()    {}
func (*Question) Descriptor() ([]byte, []int) {
	return fileDescriptor_41c67e33ca9d1f26, []int{3}
}

func (m *Question) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Question.Unmarshal(m, b)
}
func (m *Question) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Question.Marshal(b, m, deterministic)
}
func (m *Question) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Question.Merge(m, src)
}
func (m *Question) XXX_Size() int {
	return xxx_messageInfo_Question.Size(m)
}
func (m *Question) XXX_DiscardUnknown() {
	xxx_messageInfo_Question.DiscardUnknown(m)
}

var xxx_messageInfo_Question proto.InternalMessageInfo

func (m *Question) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Question) GetAnswer() string {
	if m != nil {
		return m.Answer
	}
	return ""
}

func (m *Question) GetQuestion() string {
	if m != nil {
		return m.Question
	}
	return ""
}

func (m *Question) GetTestId() string {
	if m != nil {
		return m.TestId
	}
	return ""
}

type SetQuestionResponse struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetQuestionResponse) Reset()         { *m = SetQuestionResponse{} }
func (m *SetQuestionResponse) String() string { return proto.CompactTextString(m) }
func (*SetQuestionResponse) ProtoMessage()    {}
func (*SetQuestionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_41c67e33ca9d1f26, []int{4}
}

func (m *SetQuestionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetQuestionResponse.Unmarshal(m, b)
}
func (m *SetQuestionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetQuestionResponse.Marshal(b, m, deterministic)
}
func (m *SetQuestionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetQuestionResponse.Merge(m, src)
}
func (m *SetQuestionResponse) XXX_Size() int {
	return xxx_messageInfo_SetQuestionResponse.Size(m)
}
func (m *SetQuestionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetQuestionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetQuestionResponse proto.InternalMessageInfo

func (m *SetQuestionResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func init() {
	proto.RegisterType((*Test)(nil), "test.Test")
	proto.RegisterType((*GetTestRequest)(nil), "test.GetTestRequest")
	proto.RegisterType((*SetTestResponse)(nil), "test.SetTestResponse")
	proto.RegisterType((*Question)(nil), "test.Question")
	proto.RegisterType((*SetQuestionResponse)(nil), "test.SetQuestionResponse")
}

func init() { proto.RegisterFile("testpb/test.proto", fileDescriptor_41c67e33ca9d1f26) }

var fileDescriptor_41c67e33ca9d1f26 = []byte{
	// 302 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0x4d, 0x4f, 0x83, 0x40,
	0x10, 0x0d, 0x48, 0x5a, 0x1c, 0x0d, 0xc6, 0xf5, 0x0b, 0x39, 0x35, 0x24, 0x26, 0x8d, 0x5a, 0x48,
	0xaa, 0x9e, 0x7a, 0xf3, 0x62, 0x3c, 0x0a, 0x9e, 0xbc, 0x18, 0x3e, 0xa6, 0xb8, 0xd6, 0xb2, 0x94,
	0x5d, 0x34, 0xf1, 0xff, 0xf8, 0x3f, 0xcd, 0x2e, 0x4b, 0x83, 0xd5, 0x83, 0x27, 0x66, 0xde, 0xbc,
	0x37, 0x1f, 0x8f, 0x85, 0x7d, 0x81, 0x5c, 0x54, 0x69, 0x28, 0x3f, 0x41, 0x55, 0x33, 0xc1, 0x88,
	0x25, 0x63, 0xff, 0x1c, 0xac, 0x47, 0xe4, 0x82, 0x38, 0x60, 0xd2, 0xdc, 0x35, 0x46, 0xc6, 0x78,
	0x3b, 0x32, 0x69, 0x4e, 0x08, 0x58, 0x65, 0xb2, 0x44, 0xd7, 0x54, 0x88, 0x8a, 0xfd, 0x11, 0x38,
	0x77, 0x28, 0x24, 0x3d, 0xc2, 0x55, 0xf3, 0x87, 0xca, 0xbf, 0x81, 0xbd, 0xb8, 0x63, 0xf0, 0x8a,
	0x95, 0x1c, 0xff, 0xd5, 0xb8, 0x00, 0xfb, 0x41, 0xf6, 0xa3, 0xac, 0xfc, 0xc5, 0x3f, 0x86, 0x41,
	0x52, 0xf2, 0x0f, 0xac, 0xb5, 0x42, 0x67, 0xc4, 0x03, 0x7b, 0xa5, 0x35, 0xee, 0x96, 0xaa, 0xac,
	0x73, 0x72, 0x02, 0x43, 0x79, 0xdc, 0x33, 0xcd, 0x5d, 0xab, 0x15, 0xc9, 0xf4, 0x3e, 0xf7, 0xcf,
	0xe0, 0x20, 0x46, 0xd1, 0xcd, 0xea, 0xef, 0xc8, 0x16, 0x6a, 0xa6, 0x1d, 0x99, 0x6c, 0x31, 0xfd,
	0x32, 0x60, 0x47, 0x1e, 0x11, 0x63, 0xfd, 0x4e, 0x33, 0x24, 0x17, 0x30, 0xd4, 0x87, 0x93, 0xc3,
	0x40, 0x59, 0xf8, 0xd3, 0x07, 0x0f, 0x5a, 0x54, 0x31, 0x2e, 0x61, 0xa8, 0x3d, 0x20, 0x3d, 0xd8,
	0x3b, 0x6a, 0xe3, 0x4d, 0x7b, 0x66, 0xb0, 0xdb, 0xdb, 0x88, 0x13, 0xa7, 0xa5, 0x75, 0x80, 0x77,
	0xba, 0x96, 0x6d, 0x6e, 0x3d, 0x36, 0x6e, 0xaf, 0x9f, 0xa6, 0x05, 0x15, 0x2f, 0x4d, 0x1a, 0x64,
	0x6c, 0x19, 0xbe, 0x36, 0x59, 0x92, 0xa2, 0x08, 0xab, 0xb7, 0x44, 0x7c, 0xd2, 0x89, 0xfa, 0xcb,
	0x69, 0x33, 0x9f, 0x63, 0xcd, 0x27, 0x45, 0x5d, 0x65, 0xb3, 0xf6, 0x0d, 0xa4, 0x03, 0x55, 0xb9,
	0xfa, 0x0e, 0x00, 0x00, 0xff, 0xff, 0xcc, 0x98, 0x90, 0xc1, 0x14, 0x02, 0x00, 0x00,
}
